name: "Build Armbian Installer ISO"

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      version_type:
        description: "版本类型"
        required: true
        default: "standard"
        type: choice
        options:
          - "standard"
          - "mini"

jobs:
  build-release:
    runs-on: ubuntu-22.04
    env:
      VERSION_TYPE: ${{ github.event.inputs.version_type }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: ./build.sh

      - name: "Prepare Release Assets"
        run: |
          # 根据版本类型重命名ISO文件
          if [ "$VERSION_TYPE" = "mini" ]; then
            mv output/armbian-installer-x86_64-standard.iso output/armbian-installer-x86_64-mini.iso
          fi

      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "Armbian-Installer-x86_64-ISO"
          body_path: ${{ github.workspace }}/info.md
          files: |
            output/armbian-installer-x86_64-${{ github.event.inputs.version_type }}.iso
          token: ${{ secrets.GITHUB_TOKEN }}
